### ISSUE TITLE
提个需求哈：期望`serverless.yml`支持hook属性的配置

### ISSUE THREAD

**Issue by BetterLuke** [serverless-components/tencent-framework-components#1]
我同样使用贵司的的这个组件：[tencent-website](https://github.com/serverless-components/tencent-website)，其中支持hook的配置，可以在部署前自动化的执行自定义命令，比如编译网页为纯静态文件，这让这个部署流程及其的舒适。

需求提出的背景：对基于typescript的node应用，在发布前需要预编译，甚至需要在hook的调用时，为线上的数据库基于最新的数据库schema做migrate的操作。虽然可以在调用`sls deploy`前使用shell命令来实现，但这显然造成了分离，可以说明，这件事情可以变的更好，因此，我想到了似曾相识的hook，这是我提出这个需求的一个原因。再者，hook里的动作可能我需要一个上下文，比如我需要知道此时线上数据库的连接信息，已完成数据的migrate操作。因此，我觉得对于这个组件，支持hook的设定是及其有价值哒～

**Comment by yugasun** [comment]
@BetterLuke 所有的·serverless 组件都是支持 `hook` 配置的，因为它都是依赖 [serverless/components](https://github.com/serverless/components) 项目，可以参考 https://github.com/serverless/components/blob/master/README.cn.md#%E8%BE%93%E5%85%A5 进行配置就行。

PS: [serverless/components](https://github.com/serverless/components) 项目实际上就是通过 Node.js 的 `spawn` 方法，来执行 `hook` 指定的命令。实际上开发者可以自己通过配置 `package.json` 中的 `scripts` 来实现，比如：

```json
{
  "scripts": {
    "build": "tsc -p .",
    "deploy": "npm run build && sls deploy --debug"
  }
}
```

然后在项目目录执行 `npm run deploy` 就可以实现组合的自定义的部署命令了，这样相对更加灵活可控。个人不太推荐使用 `hook`，所以文档中并未引导指出该配置。

**Comment by BetterLuke** [comment]
真心感谢，问题已解决 💯 

此issue可以关闭啦~
