### ISSUE TITLE
如何像AWS的Lambda获取当前task执行的工作目录`process.env.LAMBDA_TASK_ROOT`

### ISSUE THREAD

**Issue by BetterLuke** [serverless-components/tencent-framework-components#2]
问题背景：
部署NestJS应用时，其中ORM模块prismajs报错：
```
 f1095722b7a1419d1fde81b0443c722d        (node:7) ExperimentalWarning: The fs.promises API is experimental
2021-03-30T19:10:23.251Z        f1095722b7a1419d1fde81b0443c722d        (node:7) UnhandledPromiseRejectionWarning: 

Error: EROFS: read-only file system, chmod '/var/user/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x'
    at Object.chmodSync (fs.js:1022:3)
```

我在隔壁PrismaJS的项目的issue里发现里类似问题，他们在部署到AWS的Lambda时发生了类似错误，不过我有注意到有人分享workround：[通过转移可执行文件到tmp目录](https://github.com/prisma/prisma/issues/5023#issuecomment-713461534)，那么，在咱们腾讯云的serverless平台上，如果我像使用一样的workround解决这个问题，关键点在于如何像AWS的Lambda获取当前task执行的工作目录，比如在Lambda中 ，通过 `process.env.LAMBDA_TASK_ROOT`可以获取到当前执行的工作目录，那么这个问题，只能摆脱可以获知内部细节的官方大佬们了。拜托啦～

**Comment by yugasun** [comment]
@BetterLuke 腾讯云的 SCF 也支持类似的环境变量，可以通过 `process.env.USER_CODE_ROOT`  来获取。

**Comment by BetterLuke** [comment]
> @BetterLuke 腾讯云的 SCF 也支持类似的环境变量，可以通过 `process.env.USER_CODE_ROOT` 来获取。

真心感谢，问题已解决 💯 

---
此issue可以关闭啦~
