### ISSUE TITLE
deploy django success but run error

### ISSUE THREAD

**Issue by lanjianchun** [serverless-components/tencent-framework-components#3]
use the example/django 

run  sls deplay --debug   can see no error

then  open the url  get some error!

show the error message:

`{
errorCode: -1,
errorMessage: "Traceback (most recent call last): File "/var/runtime/python3/bootstrap.py", line 133, in init_handler func_handler = get_func_handler(file.rsplit(".", 1)[0], func) File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler mod = imp.load_module(mname, *imp.find_module(mname)) File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module return load_source(name, filename, file) File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source module = _load(spec) File "<frozen importlib._bootstrap>", line 675, in _load File "<frozen importlib._bootstrap>", line 655, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 678, in exec_module File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed File "/var/user/sl_handler.py", line 2, in <module> import djangodemo.wsgi File "/var/user/djangodemo/wsgi.py", line 12, in <module> from django.core.wsgi import get_wsgi_application ModuleNotFoundError: No module named 'django.core'",
requestId: "bb3e0897355fa75274b01f6abfac2bb6",
statusCode: 443
}`

can show more detail to deplay severless with django?

**Comment by yugasun** [comment]
This error is missing django dependencies, before deployment, you can try to run `pip3 install -r requirements.txt -t ./` firstly， and check whether all the requirements are installed.

**Comment by lanjianchun** [comment]
@yugasun In the file serverless.yml  has hook the pip install ....

app: appDemo
stage: dev
component: django
name: djangoDemo
inputs:
  src:
    hook: pip3 install -r requirements.txt -t ./
    dist: ./
    exclude:
      - .env
      - __pycache__/**
  region: ap-guangzhou
  functionConf:
    projectName: djangodemo
    name: ${name}
    runtime: Python3.6
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release


run sls deploy  can auto run command  pip3 install -r requirements.txt -t ./

>

**Comment by lanjianchun** [comment]
I just fixed the issuse!  Thanks

python=3.6

very important！

**Comment by yugasun** [comment]
That's great~
